import { mkdirSync, readFileSync, writeFileSync, copyFileSync, readdirSync } from 'node:fs';
import path from 'node:path';
const output = path.resolve('output/pages'); mkdirSync(output, { recursive: true });
const allowed = ['index.html', 'styles.css', 'app.js', 'browser-store.js', 'domain.js', 'lead-search.js', 'lead-search-ui.js'];
if (readdirSync(output).some(name => !allowed.includes(name))) throw new Error('Artefato contém arquivo inesperado; revise output/pages antes de publicar.');
const policy = `<meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src https://overpass.private.coffee/api/interpreter https://servicodados.ibge.gov.br/api/v1/localidades/estados/; base-uri 'none'; form-action 'none'">`;
const html = readFileSync('public/index.html', 'utf8').replace('<html lang="pt-BR">', '<html lang="pt-BR" data-storage="browser">').replace('<head>', `<head>\n  ${policy}`).replace('href="/#leads"', 'href="#leads"');
writeFileSync(path.join(output, 'index.html'), html);
for (const file of allowed.filter(name => name !== 'index.html')) copyFileSync(path.join('public', file), path.join(output, file));
console.log('CRM estático gerado com dados locais: sete arquivos públicos, nenhuma base ou credencial.');
